// Generates src/engine/icons/manifest.gen.ts and URL-rewritten CSS copies in
// src/styles/generated/ from the frozen legacy sources under generator/.
// Run via: corepack pnpm gen:icons

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const ICONS_CSS = join(ROOT, 'generator/css/icons.css');
const CUSTOM_ICONS_CSS = join(ROOT, 'generator/css/custom-icons.css');
const PICKER_JS = join(ROOT, 'generator/js/icons.js');
const GAME_ICONS_CSS = join(ROOT, 'generator/fonts/game-icons.css');

const OUT_MANIFEST = join(ROOT, 'src/engine/icons/manifest.gen.ts');
const OUT_STYLES_DIR = join(ROOT, 'src/styles/generated');

const TS_HEADER = '// GENERATED by scripts/generate-icon-manifest.ts — do not edit.';
const CSS_HEADER = '/* GENERATED by scripts/generate-icon-manifest.ts — do not edit. */';

// Rules shaped like: .icon-NAME { background-image: url(../icons/FILE.svg);}
// (custom-icons.css sometimes has a space before the closing brace)
const RULE_RE =
  /\.icon-([A-Za-z0-9_-]+)\s*\{\s*background-image:\s*url\(\.\.\/icons\/([^)]+)\)\s*;?\s*\}/g;

function parseIconCss(cssPath: string, map: Map<string, string>): number {
  const css = readFileSync(cssPath, 'utf8');
  let count = 0;
  for (const match of css.matchAll(RULE_RE)) {
    const name = match[1];
    const file = match[2];
    if (name === undefined || file === undefined) {
      throw new Error(`Unreachable: rule regex matched without groups in ${cssPath}`);
    }
    if (map.has(name) && map.get(name) !== `icons/${file}`) {
      console.error(`Conflicting definitions for icon "${name}" (in ${cssPath})`);
      process.exit(1);
    }
    map.set(name, `icons/${file}`);
    count += 1;
  }
  return count;
}

function parsePickerNames(jsPath: string): string[] {
  const js = readFileSync(jsPath, 'utf8');
  const arrayMatch = js.match(/icon_names\s*=\s*\[([\s\S]*)\]/);
  const body = arrayMatch?.[1];
  if (body === undefined) {
    console.error(`Could not find the icon_names array in ${jsPath}`);
    process.exit(1);
  }
  const names: string[] = [];
  for (const match of body.matchAll(/"([^"]+)"/g)) {
    const name = match[1];
    if (name === undefined) {
      throw new Error(`Unreachable: string regex matched without group in ${jsPath}`);
    }
    names.push(name);
  }
  return names;
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

// 1-2. Build the name → file map and read the picker list.
const iconFiles = new Map<string, string>();
const baseRuleCount = parseIconCss(ICONS_CSS, iconFiles);
const customRuleCount = parseIconCss(CUSTOM_ICONS_CSS, iconFiles);
const pickerNames = parsePickerNames(PICKER_JS);

// 3. Validate: every picker name must exist in the map.
const missing = pickerNames.filter((name) => !iconFiles.has(name));
if (missing.length > 0) {
  console.error(`${missing.length} picker icon name(s) have no CSS entry:`);
  for (const name of missing) {
    console.error(`  - ${name}`);
  }
  process.exit(1);
}

// 4. Emit the manifest module.
const sortedNames = [...iconFiles.keys()].sort();
const manifestLines: string[] = [];
manifestLines.push(TS_HEADER);
manifestLines.push('');
manifestLines.push('export const ICON_FILES = {');
for (const name of sortedNames) {
  manifestLines.push(`  ${quote(name)}: ${quote(iconFiles.get(name) as string)},`);
}
manifestLines.push('} as const satisfies Record<string, string>;');
manifestLines.push('');
manifestLines.push('export type IconName = keyof typeof ICON_FILES;');
manifestLines.push('');
manifestLines.push('export const ICON_PICKER_NAMES: readonly IconName[] = [');
for (const name of pickerNames) {
  manifestLines.push(`  ${quote(name)},`);
}
manifestLines.push('];');
manifestLines.push('');

mkdirSync(dirname(OUT_MANIFEST), { recursive: true });
writeFileSync(OUT_MANIFEST, manifestLines.join('\n'), 'utf8');

// 5. Emit URL-rewritten CSS copies.
mkdirSync(OUT_STYLES_DIR, { recursive: true });

function emitCss(sourcePath: string, outName: string, rewrite: (css: string) => string): void {
  const css = readFileSync(sourcePath, 'utf8');
  writeFileSync(join(OUT_STYLES_DIR, outName), `${CSS_HEADER}\n${rewrite(css)}`, 'utf8');
}

const rewriteIconUrls = (css: string): string =>
  css.replaceAll('url(../icons/', 'url(/rpg-cards/icons/');

emitCss(ICONS_CSS, 'icons.gen.css', rewriteIconUrls);
emitCss(CUSTOM_ICONS_CSS, 'custom-icons.gen.css', rewriteIconUrls);
emitCss(GAME_ICONS_CSS, 'game-icons.gen.css', (css) =>
  css.replaceAll('url("game-icons.', 'url("/rpg-cards/fonts/game-icons.'),
);

// The card/print stylesheets carry over from the frozen legacy sources
// (single source of truth until the Phase F cutover). They contain no asset
// URLs. One semantic rewrite: the legacy output page used Bootstrap 3's
// html{font-size:10px}, so rem values are rebased to their legacy pixel
// size (Nrem -> N*10px) — the new app keeps the browser's 16px root for
// Tailwind.
const rebaseRem = (css: string): string =>
  css.replace(/(\d*\.?\d+)rem\b/g, (_m, n: string) => `${parseFloat(n) * 10}px`);
emitCss(join(ROOT, 'generator/css/cards.css'), 'cards.gen.css', rebaseRem);
emitCss(join(ROOT, 'generator/css/card-size.css'), 'card-size.gen.css', rebaseRem);
emitCss(join(ROOT, 'generator/css/output.css'), 'output.gen.css', rebaseRem);
// The fork's style.css (loaded LAST on the legacy output page) carries a
// .game-icon line-height override that must keep winning the cascade.
emitCss(join(ROOT, 'generator/css/style.css'), 'style.gen.css', rebaseRem);

// 6. Summary.
console.log(`icons.css rules:        ${baseRuleCount}`);
console.log(`custom-icons.css rules: ${customRuleCount}`);
console.log(`ICON_FILES entries:     ${iconFiles.size}`);
console.log(`ICON_PICKER_NAMES:      ${pickerNames.length}`);
console.log(`Wrote ${OUT_MANIFEST}`);
console.log(`Wrote ${join(OUT_STYLES_DIR, 'icons.gen.css')}`);
console.log(`Wrote ${join(OUT_STYLES_DIR, 'custom-icons.gen.css')}`);
console.log(`Wrote ${join(OUT_STYLES_DIR, 'game-icons.gen.css')}`);
